### ISSUE TITLE
PUT and PATCH buildConfig API got empty response body

### ISSUE THREAD

**Issue by wenfahu** [nodeshift/openshift-rest-client#154]
While trying to update the openshift buildconfig with the following code:

` const res = await 
client.apis['build.openshift.io'].v1.namespaces(projectName).buildconfigs(buildName).put({body: buildconf}) `

I got this error message:

/home/wenfahu/Documents/wukong/packages/wukong-api/node_modules/kubernetes-client/lib/backends/request.js:189
          const error = new Error(res.body.message || res.body)
                                           ^

TypeError: Cannot read property 'message' of undefined
    at _request (/home/wenfahu/Documents/wukong/packages/wukong-api/node_modules/kubernetes-client/lib/backends/request.js:189:44)
    at Request.request [as _callback] (/home/wenfahu/Documents/wukong/packages/wukong-api/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/home/wenfahu/Documents/wukong/packages/wukong-api/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/wenfahu/Documents/wukong/packages/wukong-api/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/wenfahu/Documents/wukong/packages/wukong-api/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lholmquist** [comment]
if you are able to share it,  what does your `buildconf` you are passing in look like

**Comment by wenfahu** [comment]
Here's the build config JSON file!

```
{  
   "kind":"BuildConfig",
   "apiVersion":"build.openshift.io/v1",
   "metadata":{  
      "name":"adih",
      "namespace":"customer-portal-labs--build",
      "selfLink":"/apis/build.openshift.io/v1/namespaces/customer-portal-labs--build/buildconfigs/adih",
      "uid":"958cad5a-4562-11e9-96c5-001a4a1b5eaa",
      "resourceVersion":"219246600",
      "creationTimestamp":"2019-03-13T07:35:32Z",
      "labels":{  
         "app":"adih",
         "tag":"1.0.0"
      },
      "annotations":{  
         "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"build.openshift.io/v1\",\"kind\":\"BuildConfig\",\"metadata\":{\"annotations\":{\"openshift.io/generated-by\":\"OpenShiftWebConsole\"},\"labels\":{\"app\":\"adih\",\"tag\":\"1.0.0\"},\"name\":\"adih\",\"namespace\":\"customer-portal-labs--build\"},\"spec\":{\"output\":{\"pushSecret\":{\"name\":\"images-paas-push-config\"},\"to\":{\"kind\":\"DockerImage\",\"name\":\"images.paas.redhat.com/customer-portal-labs/adih:1.0.0\"}},\"postCommit\":{},\"resources\":{\"limits\":{\"cpu\":\"500m\",\"memory\":\"2Gi\"},\"requests\":{\"cpu\":\"125m\",\"memory\":\"1536Mi\"}},\"runPolicy\":\"Serial\",\"source\":{\"git\":{\"ref\":\"1.0.0\",\"uri\":\"https://gitlab.cee.redhat.com/cplabsapps/adih.git\"},\"type\":\"Git\"},\"strategy\":{\"sourceStrategy\":{\"env\":[{\"name\":\"IOJS\",\"value\":\"false\"},{\"name\":\"GIT_SSL_NO_VERIFY\",\"value\":\"true\"}],\"forcePull\":true,\"from\":{\"kind\":\"DockerImage\",\"name\":\"images.paas.redhat.com/customer-portal-labs/nodejs-6-rhel7:latest\"}},\"type\":\"Source\"},\"triggers\":[]}}\n",
         "openshift.io/generated-by":"OpenShiftWebConsole"
      }
   },
   "spec":{  
      "triggers":[  

      ],
      "runPolicy":"Serial",
      "source":{  
         "type":"Git",
         "git":{  
            "uri":"https://gitlab.cee.redhat.com/cplabsapps/adih.git",
            "ref":"1.0.0"
         }
      },
      "strategy":{  
         "type":"Source",
         "sourceStrategy":{  
            "from":{  
               "kind":"DockerImage",
               "name":"images.paas.redhat.com/customer-portal-labs/nodejs-6-rhel7:latest"
            },
            "env":[  
               {  
                  "name":"IOJS",
                  "value":"false"
               },
               {  
                  "name":"GIT_SSL_NO_VERIFY",
                  "value":"true"
               }
            ],
            "forcePull":true
         }
      },
      "output":{  
         "to":{  
            "kind":"DockerImage",
            "name":"images.paas.redhat.com/customer-portal-labs/adih:1.0.0"
         },
         "pushSecret":{  
            "name":"images-paas-push-config"
         }
      },
      "resources":{  
         "limits":{  
            "cpu":"500m",
            "memory":"2Gi"
         },
         "requests":{  
            "cpu":"125m",
            "memory":"1536Mi"
         }
      },
      "postCommit":{  

      },
      "nodeSelector":null,
      "successfulBuildsHistoryLimit":5,
      "failedBuildsHistoryLimit":5
   },
   "status":{  
      "lastVersion":15
   }
}
```

**Comment by wenfahu** [comment]
I finally figured it out. The URL of the OpenShift API server I was using then is an HTTP address. The PUT and PATCH request would return status code 302, leading to the error mentioned above. After changing it to an HTTPS URL, it works fine.
