### ISSUE TITLE
HTTP errors using 2.2.1

### ISSUE THREAD

**Issue by evanshortiss** [nodeshift/openshift-rest-client#162]
We noticed that since openshift-rest-client v2.2.1 was released nodeshift has stopped working for some of us.

I have a project setup on my machine using nodeshift to deploy and test on OpenShift and it was working great (thank you 🙏)

A colleague cloned the project and tried to use nodeshift, but the deploy failed with this error:

```
2019-09-10T18:59:12.897Z INFO loading configuration
kubernetes-client deprecated fromKubeconfig see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md#request-kubeconfig- node_modules/nodeshift/lib/nodeshift-config.js:35:32
2019-09-10T18:59:12.955Z INFO using namespace city-of-losangeles at https://master.hackfest-3ace.open.redhat.com:443
2019-09-10T18:59:12.990Z WARNING a file property was not found in your package.json, archiving the current directory.
2019-09-10T18:59:12.990Z INFO creating archive of .gitignore, Dockerfile, README.md, data, generate.js, lib, package-lock.json, package.json
2019-09-10T18:59:13.013Z ERROR this.backend.http is not a function
```

Looking at the dependency tree it seems like a new release of the openshift-rest-client was made, so it's possibly the culprit. 

The original dep setup for me was:

* nodeshift 3.1.1
  * openshift-rest-client 2.2.0
    * kubernetes-client 7.0.1

I rm'ed my lockfile and did a reinstall and ended up with:

* nodeshift 3.1.1
  * openshift-rest-client 2.2.1
    * kubernetes-client 8.3.4

Adding a log in the nodeshift source allows me to get this stacktrace:

```
TypeError: this.backend.http is not a function
    at Root._requestAsync (/Users/eshortis/workspaces/work/rhte-2019/rhte-2019-hackathon-on-rhmi/content/iot-data-generator/node_modules/swagger-fluent/lib/loader.js:239:25)
    at Root._get (/Users/eshortis/workspaces/work/rhte-2019/rhte-2019-hackathon-on-rhmi/content/iot-data-generator/node_modules/swagger-fluent/lib/loader.js:266:17)
    at Object.createOrUpdateBuildConfig (/Users/eshortis/workspaces/work/rhte-2019/rhte-2019-hackathon-on-rhmi/content/iot-data-generator/node_modules/nodeshift/lib/build-config.js:84:133)
    at build (/Users/eshortis/workspaces/work/rhte-2019/rhte-2019-hackathon-on-rhmi/content/iot-data-generator/node_modules/nodeshift/lib/goals/build.js:34:27)
```

The `get()` call in `build-config.js:84:133` triggers the error.

I'm not familiar with how the swagger module and openshift-rest-client work together, but hopefully this is helpful. Maybe it's just some

**Comment by evanshortiss** [comment]
Opening in nodeshift repo.

**Comment by evanshortiss** [comment]
Actually I think I've found a fix. In *openshift-rest-client.js* add:

```js
const Request = require('kubernetes-client/backends/request')
```

and make this change:

```
// Current code. Doesn't work
// const client = new Client({ backend: kubeconfig || kbconfig.loadFromDefault(), spec, getNames: getNames });

// Fix per https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md#preparing-to-upgrade-to-900
const client = new Client({ backend: new Request(kubeconfig) || kbconfig.loadFromDefault(), spec, getNames: getNames });
```

I'm happy to PR this.

**Comment by helio-frota** [comment]
That's weird on how the tests passed before.

> I'm happy to PR this.

Sounds great thanks!

**Comment by lholmquist** [comment]
A PR would be good, thanks.

are you specifying your own configuration?  How are you setting up the client, i guess is what i'm asking

**Comment by evanshortiss** [comment]
@lholmquist no config besides the `namespace.name` CLI flag like so `nodeshift --namespace.name my-ns`

PR opened.

**Comment by lholmquist** [comment]
I put this in your PR,  but this comment should go here

@evanshortiss i reverted the changes from that other PR #160 and released a new 2.2.2 version. you should be able to get this new updated version if you remove your package-lock and do an install again

**Comment by lholmquist** [comment]
Going to close this since 2.2.2 should fix this

**Comment by evanshortiss** [comment]
Thanks!
