### ISSUE TITLE
Specifying a Custom Config as an object fails

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/openshift-rest-client#222]
If a user passes in a custom config as an object(that is in the valid kube config format),  they will get this error:

```
TypeError: kubeconfig.getCurrentContext is not a function
    at convertKubeconfig (/var/task/node_modules/kubernetes-client/backends/request/config.js:16:30)
    at new Request (/var/task/node_modules/kubernetes-client/backends/request/client.js:118:26)
    at openshiftClient (/var/task/node_modules/openshift-rest-client/lib/openshift-rest-client.js:138:30)
    at setup (/var/task/node_modules/nodeshift/lib/nodeshift-config.js:35:28)
    at async run (/var/task/node_modules/nodeshift/bin/cli.js:36:20)
    at async Express.openShiftBuild (/var/task/openshift/openShiftBuild.js:53:3)
    at async Express.deploy (/var/task/serverless.js:68:5)
    at async Runtime.module.exports [as handler] (/opt/nodejs/node_modules/@serverless/core/handler.js:273:24)
```

It is happening here:  https://github.com/nodeshift/openshift-rest-client/blob/master/lib/openshift-rest-client.js#L145

It looks like we just need to do this instead:

```
kubeconfig.loadFromString(JSON.stringify(config));
clientConfig.backend = new Request({ kubeconfig });
```

If they don't add an `apiVersion` or `kind` then the underlying library errors,  so we could inject those properties if they are not there?

**Comment by lholmquist** [comment]
If a user passes in an actual KubeConfig object, https://github.com/nodeshift/openshift-rest-client/blob/049059de652d9467b342f465a9394f321fc960bf/index.js#L23, 

Then this wouldn't error.  They would be doing something like this:

```
const openshiftRestClient = require('openshift-rest-client').OpenshiftClient;
const k8Config = require('openshift-rest-client').config;

const config = {
  apiVersion: 'v1',
  kind: 'Config',
  clusters: [ ],
  users: [],
  contexts: [ ],
  'current-context': '...'
};

k8Config.loadFromString(JSON.stringify(config));


openshiftRestClient({config: k8Config}).then((client) => {
  console.log(client);
})
```

That is fine,  but they should also be able to pass in a regular object without having to do the `loadFromString` themselves
